### ISSUE TITLE
slpSUSTAIN bug report

### ISSUE THREAD

**Issue by ajwills72** [ajwills72/catlearn#1]
Bug report submitted by Charlotte Edmunds.The attached files below are R files, but github won't allow these, so they've been changed to .txt. Change back to .R to run.

[Error.txt](https://github.com/ajwills72/catlearn/files/2388786/Error.txt)
[training.mat.charlotte.txt](https://github.com/ajwills72/catlearn/files/2388788/training.mat.charlotte.txt)

**Comment by ajwills72** [comment]
@lenarddome

**Comment by lenarddome** [comment]
I think I figured out what is going on. The function works as it supposed to, but you get error messages (see below) because of the initial parameters are incomplete and/or incorrect. slpSUSTAIN, **being a state list processor, requires you to define both the first cluster and its weights**. If you want them to be zero, than either set each value to 0 as in `matrix(rep(0, 4), nrow = 1)` or set object to NA (see documentation).  **The solution can potentially be to add more information to and elaborate the function's documentation in future releases**. 

### **Here are the reasons for the error messages:**

If you don't define `cluster`, the function will not fill the first cluster with any value and the object will be created `NULL`. So, when it wants to calculate the stimulus distance from the cluster's position with Eq. 4 on **line 122** - it is the first instance where `cluster` is being actively used - it needs a matrix instead of an empty object. And there you get the error message:
```R
> slpSUSTAIN(st=st.all, tr=trlength[, -7], xtdo = TRUE)
  Error in matrix(0, nrow = nrow(cluster), ncol = length(unique(fac.dims))) :
  non-numeric matrix extent
```
Assuming you have `cluster = NA` and weights from above as:
```R
w = matrix(rep(NA, 4), nrow = 1)
```
Then you get an error message something like:
```R
> slpSUSTAIN(st=st.all, tr=trlength[, -7], xtdo = TRUE)
  Error in if (target[fac.queried][t.queried] < 1) new.cluster <- TRUE :
  argument is of length zero
```
Because the weights for each nominal spaces are set to NA, the output activations which are used in calculating `target`, contain only NAs (see Eq.7 on line 132). So `NA < 1` will produce nothing, therefore the argument length is zero.

So, all in all, the end of the above st should look like this:
```R
st <- (...,
       w = NA,
       cluster = NA,
       colskip = 2)
```
(`colskip` is 2 for the above training matrix.)

I hope this helps to anyone who runs into these error messages!

Best,
Lenard

**Comment by ajwills72** [comment]
Thanks, Lenard! My feeling here is that this is not a bug, as the code is working as documented. The issue may have arisen because of changes we made after Charotte first used the code but before it was available outside our lab. I agree that enhanced documentation, or error catching, could be something to consider for the next release.
